# Generated by Django 3.1.3 on 2021-04-08 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_number', models.CharField(blank=True, max_length=10)),
                ('poke_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PokeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_types', models.CharField(blank=True, max_length=10)),
                ('poke_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokeinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PokeEvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_evo', models.CharField(blank=True, max_length=10, null=True)),
                ('poke_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokeinfo')),
            ],
        ),
    ]
