# Generated by Django 3.1.3 on 2021-04-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210408_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeevo',
            name='poke_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evos', to='api.pokeinfo'),
        ),
        migrations.AlterField(
            model_name='pokeinfo',
            name='poke_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='poketype',
            name='poke_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='api.pokeinfo'),
        ),
    ]
