# Generated by Django 3.1.3 on 2021-04-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210408_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poketype',
            old_name='poke_types',
            new_name='poke_type',
        ),
    ]
