# Generated by Django 3.1.3 on 2021-04-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210408_0810'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pokeevo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pokeinfo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='poketype',
            table=None,
        ),
    ]
