# Generated by Django 3.1.3 on 2021-04-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210408_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeevo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokeinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poketype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
